/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAcompanhamentoRouteImport } from './routes/_authenticated/acompanhamento'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCustomerServiceRouteImport } from './routes/_authenticated/customer-service'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardsRouteImport } from './routes/_authenticated/dashboards'
import { Route as AuthenticatedEngenhariaRouteImport } from './routes/_authenticated/engenharia'
import { Route as AuthenticatedPlanejamentoRouteImport } from './routes/_authenticated/planejamento'
import { Route as AuthenticatedPedidosIndexRouteImport } from './routes/_authenticated/pedidos/index'
import { Route as AuthenticatedPedidosIdRouteImport } from './routes/_authenticated/pedidos/$id'
import { Route as AuthenticatedPedidosNovoRouteImport } from './routes/_authenticated/pedidos/novo'
import { Route as AuthenticatedPedidosIdConfirmacaoRouteImport } from './routes/_authenticated/pedidos/$id_.confirmacao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAcompanhamentoRoute =
  AuthenticatedAcompanhamentoRouteImport.update({
    id: '/acompanhamento',
    path: '/acompanhamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomerServiceRoute =
  AuthenticatedCustomerServiceRouteImport.update({
    id: '/customer-service',
    path: '/customer-service',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardsRoute = AuthenticatedDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEngenhariaRoute = AuthenticatedEngenhariaRouteImport.update({
  id: '/engenharia',
  path: '/engenharia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanejamentoRoute =
  AuthenticatedPlanejamentoRouteImport.update({
    id: '/planejamento',
    path: '/planejamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedidosIndexRoute =
  AuthenticatedPedidosIndexRouteImport.update({
    id: '/pedidos/',
    path: '/pedidos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedidosIdRoute = AuthenticatedPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosNovoRoute =
  AuthenticatedPedidosNovoRouteImport.update({
    id: '/pedidos/novo',
    path: '/pedidos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedidosIdConfirmacaoRoute =
  AuthenticatedPedidosIdConfirmacaoRouteImport.update({
    id: '/pedidos/$id_/confirmacao',
    path: '/pedidos/$id/confirmacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/acompanhamento': typeof AuthenticatedAcompanhamentoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/customer-service': typeof AuthenticatedCustomerServiceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dashboards': typeof AuthenticatedDashboardsRoute
  '/engenharia': typeof AuthenticatedEngenhariaRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/pedidos/novo': typeof AuthenticatedPedidosNovoRoute
  '/pedidos/': typeof AuthenticatedPedidosIndexRoute
  '/pedidos/$id/confirmacao': typeof AuthenticatedPedidosIdConfirmacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/acompanhamento': typeof AuthenticatedAcompanhamentoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/customer-service': typeof AuthenticatedCustomerServiceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dashboards': typeof AuthenticatedDashboardsRoute
  '/engenharia': typeof AuthenticatedEngenhariaRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/pedidos/novo': typeof AuthenticatedPedidosNovoRoute
  '/pedidos': typeof AuthenticatedPedidosIndexRoute
  '/pedidos/$id/confirmacao': typeof AuthenticatedPedidosIdConfirmacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/acompanhamento': typeof AuthenticatedAcompanhamentoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/customer-service': typeof AuthenticatedCustomerServiceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dashboards': typeof AuthenticatedDashboardsRoute
  '/_authenticated/engenharia': typeof AuthenticatedEngenhariaRoute
  '/_authenticated/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/_authenticated/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/_authenticated/pedidos/novo': typeof AuthenticatedPedidosNovoRoute
  '/_authenticated/pedidos/': typeof AuthenticatedPedidosIndexRoute
  '/_authenticated/pedidos/$id_/confirmacao': typeof AuthenticatedPedidosIdConfirmacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/acompanhamento'
    | '/admin'
    | '/clientes'
    | '/customer-service'
    | '/dashboard'
    | '/dashboards'
    | '/engenharia'
    | '/planejamento'
    | '/pedidos/$id'
    | '/pedidos/novo'
    | '/pedidos/'
    | '/pedidos/$id/confirmacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/acompanhamento'
    | '/admin'
    | '/clientes'
    | '/customer-service'
    | '/dashboard'
    | '/dashboards'
    | '/engenharia'
    | '/planejamento'
    | '/pedidos/$id'
    | '/pedidos/novo'
    | '/pedidos'
    | '/pedidos/$id/confirmacao'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/acompanhamento'
    | '/_authenticated/admin'
    | '/_authenticated/clientes'
    | '/_authenticated/customer-service'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboards'
    | '/_authenticated/engenharia'
    | '/_authenticated/planejamento'
    | '/_authenticated/pedidos/$id'
    | '/_authenticated/pedidos/novo'
    | '/_authenticated/pedidos/'
    | '/_authenticated/pedidos/$id_/confirmacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/acompanhamento': {
      id: '/_authenticated/acompanhamento'
      path: '/acompanhamento'
      fullPath: '/acompanhamento'
      preLoaderRoute: typeof AuthenticatedAcompanhamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customer-service': {
      id: '/_authenticated/customer-service'
      path: '/customer-service'
      fullPath: '/customer-service'
      preLoaderRoute: typeof AuthenticatedCustomerServiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboards': {
      id: '/_authenticated/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof AuthenticatedDashboardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engenharia': {
      id: '/_authenticated/engenharia'
      path: '/engenharia'
      fullPath: '/engenharia'
      preLoaderRoute: typeof AuthenticatedEngenhariaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planejamento': {
      id: '/_authenticated/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof AuthenticatedPlanejamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/': {
      id: '/_authenticated/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof AuthenticatedPedidosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/$id': {
      id: '/_authenticated/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedPedidosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/novo': {
      id: '/_authenticated/pedidos/novo'
      path: '/pedidos/novo'
      fullPath: '/pedidos/novo'
      preLoaderRoute: typeof AuthenticatedPedidosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/$id_/confirmacao': {
      id: '/_authenticated/pedidos/$id_/confirmacao'
      path: '/pedidos/$id/confirmacao'
      fullPath: '/pedidos/$id/confirmacao'
      preLoaderRoute: typeof AuthenticatedPedidosIdConfirmacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcompanhamentoRoute: typeof AuthenticatedAcompanhamentoRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedCustomerServiceRoute: typeof AuthenticatedCustomerServiceRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDashboardsRoute: typeof AuthenticatedDashboardsRoute
  AuthenticatedEngenhariaRoute: typeof AuthenticatedEngenhariaRoute
  AuthenticatedPlanejamentoRoute: typeof AuthenticatedPlanejamentoRoute
  AuthenticatedPedidosIdRoute: typeof AuthenticatedPedidosIdRoute
  AuthenticatedPedidosNovoRoute: typeof AuthenticatedPedidosNovoRoute
  AuthenticatedPedidosIndexRoute: typeof AuthenticatedPedidosIndexRoute
  AuthenticatedPedidosIdConfirmacaoRoute: typeof AuthenticatedPedidosIdConfirmacaoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcompanhamentoRoute: AuthenticatedAcompanhamentoRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedCustomerServiceRoute: AuthenticatedCustomerServiceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDashboardsRoute: AuthenticatedDashboardsRoute,
  AuthenticatedEngenhariaRoute: AuthenticatedEngenhariaRoute,
  AuthenticatedPlanejamentoRoute: AuthenticatedPlanejamentoRoute,
  AuthenticatedPedidosIdRoute: AuthenticatedPedidosIdRoute,
  AuthenticatedPedidosNovoRoute: AuthenticatedPedidosNovoRoute,
  AuthenticatedPedidosIndexRoute: AuthenticatedPedidosIndexRoute,
  AuthenticatedPedidosIdConfirmacaoRoute:
    AuthenticatedPedidosIdConfirmacaoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
